all:
  hosts:
    node1:
      ansible_host: 192.168.10.80
      ip: 192.168.10.80
      access_ip: 192.168.10.80
    node2:
      ansible_host: 192.168.10.81
      ip: 192.168.10.81
      access_ip: 192.168.10.81
    node3:
      ansible_host: 192.168.10.85
      ip: 192.168.10.85
      access_ip: 192.168.10.85
    node4:
      ansible_host: 192.168.10.86
      ip: 192.168.10.86
      access_ip: 192.168.10.86
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
  vars:
    ansible_user: root
