all:
  hosts:
    node1:
      ansible_host: 192.168.32.31
      ip: 192.168.32.31
      access_ip: 192.168.32.31
    node2:
      ansible_host: 192.168.32.32
      ip: 192.168.32.32
      access_ip: 192.168.32.32
    node3:
      ansible_host: 192.168.32.33
      ip: 192.168.32.33
      access_ip: 192.168.32.33
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
  vars:
    ansible_user: root
